import os
import pandas as pd
from src.utils.metrics_helpers import normalize_inverse, compute_stability_score

"""
NavStatsEngine
Purpose:
- Compute NAV performance metrics (Drift, Stability)
- Generate ML-ready feature set for the GSoC Classifier
"""

class NavStatsEngine:

    @staticmethod
    def calculate_metrics(df):
        """
        Calculates P95 Drift and Stability.
        Uses helpers from metrics_helpers.py.
        """
        if df is None or df.empty:
            return {
                "p95_drift": 0.0,
                "stability_score": 0.0,
                "nav_score": 0.0,
                "total_score": 0.0,
                "sample_count": 0
            }

        # ------------------------------------------------
        # ALTITUDE DRIFT
        # ------------------------------------------------
        # Comparing current Alt to the start of the mission
        alt_series = df["RelHomeAlt"].dropna()

        if alt_series.empty:
            p95_drift = 0.0
        else:
            start_alt = alt_series.iloc[0]
            alt_error = (alt_series - start_alt).abs()
            p95_drift = float(alt_error.quantile(0.95))
        # Use normalize_inverse to score the drift
        nav_score = normalize_inverse(p95_drift, worst=15.0, best=0.0)
        # ------------------------------------------------
        # STABILITY METRIC
        # ------------------------------------------------
        # compute_stability_score returns a NEW dataframe with stability columns added
        df_stable = compute_stability_score(df, cols=["Roll", "Pitch"])

        # Access the new columns generated by the helper
        stability_cols = ["roll_stability", "pitch_stability"]
        avg_stability = df_stable[stability_cols].mean().mean()

        # ------------------------------------------------
        # FINAL NAV SCORE (50% Nav Accuracy, 50% Smoothness)
        # ------------------------------------------------
        total_score = (nav_score + avg_stability) / 2

        return {
            "p95_drift": float(round(p95_drift, 3)),
            "stability_score": float(round(avg_stability, 2)),
            "nav_score": float(round(nav_score, 2)),
            "total_score": float(round(total_score, 2)),
            "sample_count": int(len(df))
        }

    @staticmethod
    def generate_features(df):
        """
        FEATURE GENERATION FOR ML DATASET
        Transforms raw NAV rows into a statistical feature set.
        """
        if df is None or df.empty:
            return pd.DataFrame()

        features = {}

        # Speed statistics
        if "Spd" in df.columns:
            features["speed_mean"] = df["Spd"].mean()
            features["speed_std"] = df["Spd"].std()

        # Satellite statistics
        if "NSats" in df.columns:
            features["sat_mean"] = df["NSats"].mean()
            features["sat_min"] = df["NSats"].min()

        # GPS accuracy
        if "HDop" in df.columns:
            features["hdop_mean"] = df["HDop"].mean()
            features["hdop_max"] = df["HDop"].max()

        # Altitude variation
        if "Alt" in df.columns:
            features["alt_range"] = df["Alt"].max() - df["Alt"].min()

        # Velocity stability (3D Vector Magnitude)
        if {"VN", "VE", "VD"}.issubset(df.columns):
            vel_mag = (df["VN"]**2 + df["VE"]**2 + df["VD"]**2) ** 0.5
            features["velocity_mean"] = vel_mag.mean()
            features["velocity_std"] = vel_mag.std()

        # Return as a single-row DataFrame for the mission
        return pd.DataFrame([features])

if __name__ == "__main__":
    # Test block to verify with NavDataService
    from nav_data_service import NavDataService

    service = NavDataService()
    raw_df = service.get_state_report()

    if not raw_df.empty:
        stats = NavStatsEngine.calculate_metrics(raw_df)
        ml_features = NavStatsEngine.generate_features(raw_df)

        print("--- Mission Metrics ---")
        print(stats)
        print("\n--- ML Features ---")
        print(ml_features)
    else:
        print("No data found to process.")