import pandas as pd
from src.utils.metrics_helpers import normalize_inverse, compute_stability_score

class NavStatsEngine:
    @staticmethod
    def calculate_metrics(df):
        """
        Calculates P95 Drift and Stability.
        Uses helpers from metrics_helpers.py.
        """
        if df is None or df.empty:
            return {"p95_drift": 0.0, "stability_score": 0.0, "score": 0.0}

        # 1. Calculate Drift
        # Comparing current Alt to the start of the mission
        df['alt_error'] = (df['Alt'] - df['Alt'].iloc[0]).abs()
        p95_drift = float(df['alt_error'].quantile(0.95))

        # 2. Use normalize_inverse to score the drift
        nav_score = normalize_inverse(p95_drift, worst=1.5, best=0.0)

        # 3. ACTIVATE: compute_stability_score
        # This function returns a NEW dataframe with stability columns added
        df_stable = compute_stability_score(df, cols=['Roll', 'Pitch'])

        # Now we access the new columns generated by the helper:
        stability_cols = ['roll_stability', 'pitch_stability']
        avg_stability = df_stable[stability_cols].mean().mean()

        # 4. Final Aggregated Score (50% Nav Accuracy, 50% Smoothness)
        total_score = (nav_score + avg_stability) / 2

        return {
            "p95_drift": round(p95_drift, 3),
            "stability_score": round(avg_stability, 2),
            "nav_score": round(nav_score, 2),
            "total_score": round(total_score, 2),
            "sample_count": len(df)
        }